name: Deploy App to Azure App Service

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List repository structure
        run: |
            pwd
            ls -R

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./src/Api/Api.csproj -c Release --no-restore

      - name: Test
        run: dotnet test -c Release

      - name: Publish
        run: dotnet publish ./src/Api/Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production   # approval
    steps:
       - name: Azure Login
         uses: azure/login@v2
         with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

       - name: Fetch DB Connection String
         id: keyvault
         uses: Azure/get-keyvault-secrets@v1
         with:
          keyvault: Buzzy-dev-kv
          secrets: DBConnectionString

       - name: Set App Service Connection String
         run: |
          az webapp config connection-string set \
          --name Buzzy-dev-app \
          --resource-group Buzzy-dev-rg \
          --connection-string-type PostgreSQL \
          --settings "DefaultConnection=${{ steps.keyvault.outputs.DBConnectionString }}"
       

       - name: Download artifact
         uses: actions/download-artifact@v4
         with:
            name: .net-app

       - name: Deploy to Azure WebApp
         uses: azure/webapps-deploy@v3
         with:
          app-name: "Buzzy-dev-app"
          slot-name: 'Production'
          package: .

