name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        working-directory: infra
        env:
          TF_VAR_db_admin_password: "${{ secrets.PG_ADMIN_PASSWORD }}"
          TF_VAR_environment: "dev"
          TF_VAR_project_name: "Buzzy"
        run: terraform apply -input=false -auto-approve tfplan

