name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_db_admin_password: ${{ secrets.PG_ADMIN_PASSWORD }}
      TF_VAR_azure_credentials_json: ${{ secrets.AZURE_CREDENTIALS }}
      TF_VAR_environment: dev
      TF_VAR_project_name: Buzzy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: Terraform Import Resource Group
        working-directory: infra
        run: terraform import azurerm_resource_group.rg /subscriptions/ca001ed5-8efc-40e9-bb2a-4dc688ec49cd/resourceGroups/Buzzy-dev-rg

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -input=false -auto-approve tfplan
